name: HACS Validation

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: hacs/action@main
        with:
          repository: svante-jacobsen/loggamera-home-assistant
          category: integration
