name: Update manifest version

on:
  push:
    tags:
      - 'v*'

jobs:
  update-manifest:
    name: Update version in manifest.json
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Extract version from tag
        id: version
        run: |
          echo "VERSION=${GITHUB_REF#refs/tags/v}" >> "$GITHUB_ENV"

      - name: Update manifest.json version
        run: |
          jq ".version = \"${VERSION}\"" custom_components/loggamera/manifest.json > tmp.$$.json && mv tmp.$$.json custom_components/loggamera/manifest.json

      - name: Commit and push manifest update
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add custom_components/loggamera/manifest.json
          git commit -m "chore: update manifest version to ${VERSION}"
          git push
